name: Build and Deploy via Jenkins

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  build:
    name: Build WAR with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # or adopt, zulu, etc.
          java-version: '17'       # change to your required version

      - name: Build with Maven
        run: mvn clean install

